{% set name = "dustgoggles" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dustgoggles-{{ version }}.tar.gz
  sha256: 15d1b1eb23d7b0d1c09aa800248e093ba78c590f916652c6b58fa63a90fd66da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - cytoolz
    - python >=3.9

test:
  imports:
    - dustgoggles
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/millionconcepts/dustgoggles
  summary: ready for anything in these goggles -- a marslab project 
  description: dustgoggles is a utility library for the `marslab` ecosystem. It contains a variety of generic utilities, text-parsing tools, a framework for domain-specific functional languages, and an in-memory cache framework.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-stclair
